# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		ype
tagline:	'a blog about stuff'
description:	'A blog about stuff, and code, and electronics, and other stuff.'
url:		http://ype.env.sh

author:
  name:		'anton'
  url:		https://ype.env.sh

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/sewKit.jpg

social:
  - icon:	github
    url:	https://github.com/ype
    desc:	Fork me

  - icon:	feed
    url:	http://ype.env.sh/atom.xml
    desc:	Feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

  - title:      Archive
    url:        /archive

copyright:
  author:	anton
  url:		http://ype.env.sh
  type_title:	Some rights might be reserved, who really cares?
  type_url:	http://www.wtfpl.net/
